<a href="https://colab.research.google.com/github/TongSii/hds5210-2025/blob/main/week11/module31_filter_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**single-value-filter**

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('complications.csv')

In [3]:
data['city'].value_counts()

city
BIRMINGHAM        76
MONTGOMERY        38
DOTHAN            38
GADSDEN           38
ANNISTON          38
MOBILE            38
LUVERNE           19
ALABASTER         19
FORT PAYNE        19
SHEFFIELD         19
OPP               19
BOAZ              19
FLORENCE          19
OPELIKA           19
CENTRE            19
OZARK             19
CULLMAN           19
ANDALUSIA         19
HUNTSVILLE        19
HAMILTON          19
TALLASSEE         19
ENTERPRISE        19
EUTAW             19
DADEVILLE         19
CENTREVILLE       19
MOULTON           19
SCOTTSBORO        19
GENEVA            19
FAYETTE           19
ALEXANDER CITY    19
EUFAULA           19
ATHENS            19
ASHLAND           19
FOLEY             19
DECATUR           19
WINFIELD          19
JASPER            19
GROVE HILL        19
TUSCALOOSA        19
GREENSBORO        19
WETUMPKA          19
BREWTON           19
FAIRHOPE          19
TALLADEGA         19
CAMDEN            12
Name: count, dtype: int64

In [4]:
filter = data['city'] == 'DADEVILLE'

In [5]:
filter.value_counts()

city
False    981
True      19
Name: count, dtype: int64

In [7]:
data_DADEVILLE = data[filter]

In [9]:
data_DADEVILLE.head()

,provider_id,hospital_name,address,city,state,zip_code,county_name,phone_number,measure_id,measure_name,compared_to_national,denominator,score,lower_estimate,higher_estimate,footnote,measure_start_date,measure_end_date
513,10052,LAKE MARTIN COMMUNITY HOSPITAL,201 MARIARDEN ROAD,DADEVILLE,AL,36853,TALLAPOOSA,(256) 825-7821,COMP_HIP_KNEE,Rate of complications for hip/knee replacement...,Not Available,Not Available,Not Available,Not Available,Not Available,5.0,2015-04-01T00:00:00.000,2018-03-31T00:00:00.000
514,10052,LAKE MARTIN COMMUNITY HOSPITAL,201 MARIARDEN ROAD,DADEVILLE,AL,36853,TALLAPOOSA,(256) 825-7821,MORT_30_AMI,Death rate for heart attack patients,Number of Cases Too Small,Not Available,Not Available,Not Available,Not Available,1.0,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
515,10052,LAKE MARTIN COMMUNITY HOSPITAL,201 MARIARDEN ROAD,DADEVILLE,AL,36853,TALLAPOOSA,(256) 825-7821,MORT_30_CABG,Death rate for CABG surgery patients,Not Available,Not Available,Not Available,Not Available,Not Available,5.0,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
516,10052,LAKE MARTIN COMMUNITY HOSPITAL,201 MARIARDEN ROAD,DADEVILLE,AL,36853,TALLAPOOSA,(256) 825-7821,MORT_30_COPD,Death rate for COPD patients,No Different Than the National Rate,65,8.1,5.5,11.7,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
517,10052,LAKE MARTIN COMMUNITY HOSPITAL,201 MARIARDEN ROAD,DADEVILLE,AL,36853,TALLAPOOSA,(256) 825-7821,MORT_30_HF,Death rate for heart failure patients,Number of Cases Too Small,Not Available,Not Available,Not Available,Not Available,1.0,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000

In [8]:
data_DADEVILLE['state'].unique()

array(['AL'], dtype=object)

In [11]:
data_DADEVILLE['city'].unique()

array(['DADEVILLE'], dtype=object)

In [12]:
data_DADEVILLE.shape

(19, 18)

In [13]:
data_no = data[~filter]

In [14]:
len(data_no)

981

In [15]:
data_no.shape

(981, 18)

# RegEx Filtering

In [16]:
med_center_filter = data['hospital_name'].str.contains('CENTER$')#all the hospital that name has  "CENTER",$:end
med_centers = data[med_center_filter]

In [17]:
med_centers.shape

(456, 18)

In [18]:
med_centers['hospital_name'].value_counts()

hospital_name
SOUTHEAST ALABAMA MEDICAL CENTER              19
NORTH ALABAMA MEDICAL CENTER                  19
DEKALB REGIONAL MEDICAL CENTER                19
SHELBY BAPTIST MEDICAL CENTER                 19
DALE MEDICAL CENTER                           19
FLOYD CHEROKEE MEDICAL CENTER                 19
EAST ALABAMA MEDICAL CENTER                   19
CULLMAN REGIONAL MEDICAL CENTER               19
GADSDEN REGIONAL MEDICAL CENTER               19
MARION REGIONAL MEDICAL CENTER                19
FAYETTE MEDICAL CENTER                        19
RIVERVIEW REGIONAL MEDICAL CENTER             19
BIBB MEDICAL CENTER                           19
LAWRENCE MEDICAL CENTER                       19
HIGHLANDS MEDICAL CENTER                      19
WIREGRASS MEDICAL CENTER                      19
RUSSELL MEDICAL CENTER                        19
NORTHEAST ALABAMA REGIONAL MEDICAL CENTER     19
SOUTH BALDWIN REGIONAL MEDICAL CENTER         19
NORTHWEST MEDICAL CENTER                      19
UNIVERSITY OF SOUTH ALABAMA MEDICAL CENTER    19
WALKER BAPTIST MEDICAL CENTER                 19
D C H REGIONAL MEDICAL CENTER                 19
CITIZENS BAPTIST MEDICAL CENTER               19
Name: count, dtype: int64

In [19]:
med_centers

,provider_id,hospital_name,address,city,state,zip_code,county_name,phone_number,measure_id,measure_name,compared_to_national,denominator,score,lower_estimate,higher_estimate,footnote,measure_start_date,measure_end_date
0,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,COMP_HIP_KNEE,Rate of complications for hip/knee replacement...,No Different Than the National Rate,292,3.2,2.1,4.8,NaN,2015-04-01T00:00:00.000,2018-03-31T00:00:00.000
1,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,MORT_30_AMI,Death rate for heart attack patients,No Different Than the National Rate,688,13,11.0,15.5,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
2,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,MORT_30_CABG,Death rate for CABG surgery patients,No Different Than the National Rate,291,4.3,2.6,6.8,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
3,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,MORT_30_COPD,Death rate for COPD patients,No Different Than the National Rate,411,8.8,6.7,11.4,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
4,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,MORT_30_HF,Death rate for heart failure patients,No Different Than the National Rate,869,12.7,10.7,15.0,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,10101,CITIZENS BAPTIST MEDICAL CENTER,604 STONE AVENUE,TALLADEGA,AL,35161,TALLADEGA,(256) 761-4542,PSI_4_SURG_COMP,Deaths among Patients with Serious Treatable C...,Number of Cases Too Small,Not Available,Not Available,Not Available,Not Available,1.0,2016-07-01T00:00:00.000,2018-06-30T00:00:00.000
984,10101,CITIZENS BAPTIST MEDICAL CENTER,604 STONE AVENUE,TALLADEGA,AL,35161,TALLADEGA,(256) 761-4542,PSI_6_IAT_PTX,Collapsed lung due to medical treatment,No Different Than the National Rate,1298,0.26,0.03,0.49,NaN,2016-07-01T00:00:00.000,2018-06-30T00:00:00.000
985,10101,CITIZENS BAPTIST MEDICAL CENTER,604 STONE AVENUE,TALLADEGA,AL,35161,TALLADEGA,(256) 761-4542,PSI_8_POST_HIP,Broken hip from a fall after surgery,No Different Than the National Rate,1078,0.11,0.01,0.2,NaN,2016-07-01T00:00:00.000,2018-06-30T00:00:00.000
986,10101,CITIZENS BAPTIST MEDICAL CENTER,604 STONE AVENUE,TALLADEGA,AL,35161,TALLADEGA,(256) 761-4542,PSI_90_SAFETY,Serious complications,No Different Than the National Value,Not Available,0.93,0.5,1.37,NaN,2016-07-01T00:00:00.000,2018-06-30T00:00:00.000
987,10101,CITIZENS BAPTIST MEDICAL CENTER,604 STONE AVENUE,TALLADEGA,AL,35161,TALLADEGA,(256) 761-4542,PSI_9_POST_HEM,Perioperative Hemorrhage or Hematoma Rate,No Different Than the National Rate,85,2.50,1,3.99,NaN,2016-07-01T00:00:00.000,2018-06-30T00:00:00.000

In [20]:
hospital_filter = data['hospital_name'].str.contains('HOSPITAL')
hospitals = data[hospital_filter]

In [21]:
hospitals.shape

(411, 18)

In [24]:
hospitals['hospital_name'].value_counts()

hospital_name
MIZELL MEMORIAL HOSPITAL                  19
CRENSHAW COMMUNITY HOSPITAL               19
UAB CALLAHAN EYE HOSPITAL AUTHORITY       19
HELEN KELLER MEMORIAL HOSPITAL            19
JACKSON HOSPITAL & CLINIC INC             19
UNIVERSITY OF ALABAMA HOSPITAL            19
COMMUNITY HOSPITAL INC                    19
STRINGFELLOW MEMORIAL HOSPITAL            19
HUNTSVILLE HOSPITAL                       19
GREENE COUNTY HOSPITAL                    19
LAKE MARTIN COMMUNITY HOSPITAL            19
FLOWERS HOSPITAL                          19
CLAY COUNTY HOSPITAL                      19
ATHENS LIMESTONE HOSPITAL                 19
DECATUR MORGAN HOSPITAL-DECATUR CAMPUS    19
PROVIDENCE HOSPITAL                       19
GROVE HILL MEMORIAL HOSPITAL              19
HALE COUNTY HOSPITAL                      19
ELMORE COMMUNITY HOSPITAL                 19
D W MCMILLAN MEMORIAL HOSPITAL            19
THOMAS HOSPITAL                           19
J PAUL JONES HOSPITAL                     12
Name: count, dtype: int64

In [25]:
unknown = data[~hospital_filter & ~med_center_filter]

In [26]:
unknown['hospital_name'].unique()

array(['MARSHALL MEDICAL CENTERS SOUTH CAMPUS', "ST VINCENT'S EAST",
       'BAPTIST MEDICAL CENTER SOUTH', 'ANDALUSIA HEALTH',
       'MEDICAL CENTER ENTERPRISE', "ST VINCENT'S BIRMINGHAM",
       'MEDICAL CENTER BARBOUR'], dtype=object)

In [ ]:
data[~(hospital_filter | med_center_filter)]['hospital_name'].unique()

array(['MARSHALL MEDICAL CENTERS SOUTH CAMPUS', "ST VINCENT'S EAST",
       'BAPTIST MEDICAL CENTER SOUTH', 'ANDALUSIA HEALTH',
       'MEDICAL CENTER ENTERPRISE', "ST VINCENT'S BIRMINGHAM",
       'MEDICAL CENTER BARBOUR'], dtype=object)

#**Complex filter**

In [27]:
data['compared_to_national'].value_counts()

compared_to_national
No Different Than the National Rate     666
Not Available                           143
Number of Cases Too Small               114
No Different Than the National Value     50
Worse Than the National Rate             22
Better Than the National Rate             3
Worse Than the National Value             1
Better Than the National Value            1
Name: count, dtype: int64

# Multiple Filters

Where the **Compared to National** is not `Number of Cases Too Small` and the Denominator is not `Not Available`, except we want all the mortality related measures regardless of those first two rules.

In [28]:
data['measure_id'].unique()

array(['COMP_HIP_KNEE', 'MORT_30_AMI', 'MORT_30_CABG', 'MORT_30_COPD',
       'MORT_30_HF', 'MORT_30_PN', 'MORT_30_STK', 'PSI_10_POST_KIDNEY',
       'PSI_11_POST_RESP', 'PSI_12_POSTOP_PULMEMB_DVT',
       'PSI_13_POST_SEPSIS', 'PSI_14_POSTOP_DEHIS', 'PSI_15_ACC_LAC',
       'PSI_3_ULCER', 'PSI_4_SURG_COMP', 'PSI_6_IAT_PTX',
       'PSI_8_POST_HIP', 'PSI_90_SAFETY', 'PSI_9_POST_HEM'], dtype=object)

In [29]:
too_small = data['compared_to_national'] == 'Number of Cases Too Small'
not_avail = data['denominator'] == 'Not Available'
mortality = data['measure_id'].str.contains("^MORT")

In [30]:
data.shape

(1000, 18)

In [31]:
data[too_small].shape

(114, 18)

In [ ]:
data[not_avail].shape

(309, 18)

In [32]:
data[mortality].shape

(318, 18)

In [34]:
subset = data[mortality | (~too_small & ~not_avail)]

In [35]:
subset.shape

(785, 18)

In [37]:
subset['measure_id'].value_counts()

measure_id
MORT_30_AMI                  53
MORT_30_CABG                 53
MORT_30_STK                  53
MORT_30_COPD                 53
MORT_30_HF                   53
MORT_30_PN                   53
PSI_6_IAT_PTX                52
PSI_8_POST_HIP               52
PSI_3_ULCER                  52
PSI_12_POSTOP_PULMEMB_DVT    41
PSI_9_POST_HEM               41
PSI_15_ACC_LAC               40
PSI_14_POSTOP_DEHIS          39
PSI_10_POST_KIDNEY           33
PSI_13_POST_SEPSIS           32
PSI_11_POST_RESP             32
COMP_HIP_KNEE                30
PSI_4_SURG_COMP              23
Name: count, dtype: int64

In [38]:
subset['compared_to_national'].value_counts()

compared_to_national
No Different Than the National Rate    666
Number of Cases Too Small               54
Not Available                           40
Worse Than the National Rate            22
Better Than the National Rate            3
Name: count, dtype: int64

In [ ]:
subset['denominator'].value_counts()

29     5
85     4
73     3
79     3
113    3
      ..
612    1
502    1
70     1
158    1
385    1
Name: denominator, Length: 182, dtype: int64

In [ ]:
subset.head()

,provider_id,hospital_name,address,city,state,zip_code,county_name,phone_number,measure_id,measure_name,compared_to_national,denominator,score,lower_estimate,higher_estimate,footnote,measure_start_date,measure_end_date
1,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,MORT_30_AMI,Death rate for heart attack patients,No Different Than the National Rate,688,13,11.0,15.5,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
2,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,MORT_30_CABG,Death rate for CABG surgery patients,No Different Than the National Rate,291,4.3,2.6,6.8,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
3,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,MORT_30_COPD,Death rate for COPD patients,No Different Than the National Rate,411,8.8,6.7,11.4,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
4,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,MORT_30_HF,Death rate for heart failure patients,No Different Than the National Rate,869,12.7,10.7,15.0,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
5,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,MORT_30_PN,Death rate for pneumonia patients,No Different Than the National Rate,560,17,14.4,20.0,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000

In [39]:
subset[mortality & too_small].head()

/tmp/ipython-input-355243577.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  subset[mortality & too_small].head()

,provider_id,hospital_name,address,city,state,zip_code,county_name,phone_number,measure_id,measure_name,compared_to_national,denominator,score,lower_estimate,higher_estimate,footnote,measure_start_date,measure_end_date
58,10007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,COVINGTON,(334) 493-3541,MORT_30_AMI,Death rate for heart attack patients,Number of Cases Too Small,Not Available,Not Available,Not Available,Not Available,1.0,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
77,10008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,CRENSHAW,(334) 335-3374,MORT_30_AMI,Death rate for heart attack patients,Number of Cases Too Small,Not Available,Not Available,Not Available,Not Available,1.0,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
82,10008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,CRENSHAW,(334) 335-3374,MORT_30_STK,Death rate for stroke patients,Number of Cases Too Small,Not Available,Not Available,Not Available,Not Available,1.0,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
191,10021,DALE MEDICAL CENTER,126 HOSPITAL AVE,OZARK,AL,36360,DALE,(334) 774-2601,MORT_30_AMI,Death rate for heart attack patients,Number of Cases Too Small,Not Available,Not Available,Not Available,Not Available,1.0,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
196,10021,DALE MEDICAL CENTER,126 HOSPITAL AVE,OZARK,AL,36360,DALE,(334) 774-2601,MORT_30_STK,Death rate for stroke patients,Number of Cases Too Small,Not Available,Not Available,Not Available,Not Available,1.0,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000

In [40]:
subset[mortality & too_small].shape

/tmp/ipython-input-1630061749.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  subset[mortality & too_small].shape

(54, 18)

In [ ]:
data[data['city'] == 'DADEVILLE' | data['city'] == 'BIRMINGHAM']

In [ ]:
birmingham = data['city'] == 'BIRMINGHAM'
dadeville = data['city'] == 'DADEVILLE'
data[birmingham | dadeville]

data[birmingham | dadeville]['city'].value_counts()

BIRMINGHAM    76
DADEVILLE     19
Name: city, dtype: int64

# DataFrame.query()

In [ ]:
data.query('city in ("DADEVILLE", "BIRMINGHAM")')

,provider_id,hospital_name,address,city,state,zip_code,county_name,phone_number,measure_id,measure_name,compared_to_national,denominator,score,lower_estimate,higher_estimate,footnote,measure_start_date,measure_end_date
95,10011,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,JEFFERSON,(205) 838-3122,COMP_HIP_KNEE,Rate of complications for hip/knee replacement...,No Different Than the National Rate,107,2.9,1.7,4.7,NaN,2015-04-01T00:00:00.000,2018-03-31T00:00:00.000
96,10011,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,JEFFERSON,(205) 838-3122,MORT_30_AMI,Death rate for heart attack patients,No Different Than the National Rate,170,14.8,11.7,18.4,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
97,10011,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,JEFFERSON,(205) 838-3122,MORT_30_CABG,Death rate for CABG surgery patients,No Different Than the National Rate,103,3,1.6,5.3,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
98,10011,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,JEFFERSON,(205) 838-3122,MORT_30_COPD,Death rate for COPD patients,No Different Than the National Rate,257,10.5,8.0,13.6,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
99,10011,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,JEFFERSON,(205) 838-3122,MORT_30_HF,Death rate for heart failure patients,No Different Than the National Rate,400,11.3,9.0,13.8,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
565,10056,ST VINCENT'S BIRMINGHAM,810 ST VINCENT'S DRIVE,BIRMINGHAM,AL,35205,JEFFERSON,(205) 939-7000,PSI_4_SURG_COMP,Deaths among Patients with Serious Treatable C...,No Different Than the National Rate,153,161.36,123.41,199.31,NaN,2016-07-01T00:00:00.000,2018-06-30T00:00:00.000
566,10056,ST VINCENT'S BIRMINGHAM,810 ST VINCENT'S DRIVE,BIRMINGHAM,AL,35205,JEFFERSON,(205) 939-7000,PSI_6_IAT_PTX,Collapsed lung due to medical treatment,No Different Than the National Rate,10106,0.26,0.07,0.46,NaN,2016-07-01T00:00:00.000,2018-06-30T00:00:00.000
567,10056,ST VINCENT'S BIRMINGHAM,810 ST VINCENT'S DRIVE,BIRMINGHAM,AL,35205,JEFFERSON,(205) 939-7000,PSI_8_POST_HIP,Broken hip from a fall after surgery,No Different Than the National Rate,9282,0.11,0.02,0.19,NaN,2016-07-01T00:00:00.000,2018-06-30T00:00:00.000
568,10056,ST VINCENT'S BIRMINGHAM,810 ST VINCENT'S DRIVE,BIRMINGHAM,AL,35205,JEFFERSON,(205) 939-7000,PSI_90_SAFETY,Serious complications,No Different Than the National Value,Not Available,0.98,0.77,1.2,NaN,2016-07-01T00:00:00.000,2018-06-30T00:00:00.000
569,10056,ST VINCENT'S BIRMINGHAM,810 ST VINCENT'S DRIVE,BIRMINGHAM,AL,35205,JEFFERSON,(205) 939-7000,PSI_9_POST_HEM,Perioperative Hemorrhage or Hematoma Rate,No Different Than the National Rate,4662,2.42,1.31,3.54,NaN,2016-07-01T00:00:00.000,2018-06-30T00:00:00.000

In [ ]:
data.head()

In [41]:
data.query('city == "DADEVILLE" and state == "AL"').head()

,provider_id,hospital_name,address,city,state,zip_code,county_name,phone_number,measure_id,measure_name,compared_to_national,denominator,score,lower_estimate,higher_estimate,footnote,measure_start_date,measure_end_date
513,10052,LAKE MARTIN COMMUNITY HOSPITAL,201 MARIARDEN ROAD,DADEVILLE,AL,36853,TALLAPOOSA,(256) 825-7821,COMP_HIP_KNEE,Rate of complications for hip/knee replacement...,Not Available,Not Available,Not Available,Not Available,Not Available,5.0,2015-04-01T00:00:00.000,2018-03-31T00:00:00.000
514,10052,LAKE MARTIN COMMUNITY HOSPITAL,201 MARIARDEN ROAD,DADEVILLE,AL,36853,TALLAPOOSA,(256) 825-7821,MORT_30_AMI,Death rate for heart attack patients,Number of Cases Too Small,Not Available,Not Available,Not Available,Not Available,1.0,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
515,10052,LAKE MARTIN COMMUNITY HOSPITAL,201 MARIARDEN ROAD,DADEVILLE,AL,36853,TALLAPOOSA,(256) 825-7821,MORT_30_CABG,Death rate for CABG surgery patients,Not Available,Not Available,Not Available,Not Available,Not Available,5.0,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
516,10052,LAKE MARTIN COMMUNITY HOSPITAL,201 MARIARDEN ROAD,DADEVILLE,AL,36853,TALLAPOOSA,(256) 825-7821,MORT_30_COPD,Death rate for COPD patients,No Different Than the National Rate,65,8.1,5.5,11.7,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
517,10052,LAKE MARTIN COMMUNITY HOSPITAL,201 MARIARDEN ROAD,DADEVILLE,AL,36853,TALLAPOOSA,(256) 825-7821,MORT_30_HF,Death rate for heart failure patients,Number of Cases Too Small,Not Available,Not Available,Not Available,Not Available,1.0,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000

# Generic Complex Filtering

Apply some generic function to an entire row to figure out if should be filtered.

In [50]:
with_score = data[(data['score'] != 'Not Available') & (data['denominator'] != 'Not Available')]

In [44]:
mask = with_score.apply(lambda x: (float(x['score']) / float(x['denominator'])) > 0.10, axis=1)#row

In [46]:
with_score.shape

(691, 18)

In [47]:
with_score[mask].shape

(113, 18)

In [48]:
with_score[mask].head()

,provider_id,hospital_name,address,city,state,zip_code,county_name,phone_number,measure_id,measure_name,compared_to_national,denominator,score,lower_estimate,higher_estimate,footnote,measure_start_date,measure_end_date
14,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,PSI_4_SURG_COMP,Deaths among Patients with Serious Treatable C...,No Different Than the National Rate,185,163.11,127.1,199.11,NaN,2016-07-01T00:00:00.000,2018-06-30T00:00:00.000
20,10005,MARSHALL MEDICAL CENTERS SOUTH CAMPUS,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,(256) 593-8310,MORT_30_AMI,Death rate for heart attack patients,No Different Than the National Rate,80,14.8,11.6,18.8,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
33,10005,MARSHALL MEDICAL CENTERS SOUTH CAMPUS,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,(256) 593-8310,PSI_4_SURG_COMP,Deaths among Patients with Serious Treatable C...,Worse Than the National Rate,54,219.04,170.43,267.66,NaN,2016-07-01T00:00:00.000,2018-06-30T00:00:00.000
52,10006,NORTH ALABAMA MEDICAL CENTER,1701 VETERANS DRIVE,FLORENCE,AL,35630,LAUDERDALE,(256) 768-8400,PSI_4_SURG_COMP,Deaths among Patients with Serious Treatable C...,Worse Than the National Rate,114,207.61,166.63,248.6,NaN,2016-07-01T00:00:00.000,2018-06-30T00:00:00.000
61,10007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,COVINGTON,(334) 493-3541,MORT_30_HF,Death rate for heart failure patients,No Different Than the National Rate,85,15.6,11.1,21.7,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000

#**PandasSQL**

In [56]:
!pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.44)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26773 sha256=5016844f046a43e03863339577378691575c7581fa8e5eb31a2c629d6f909a81
  Stored in directory: /root/.cache/pip/wheels/15/a1/e7/6f92f295b5272ae5c02365e6b8fa19cb93f16a537090a1cf27
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [57]:
import pandasql as ps

In [58]:
data = pd.read_csv('complications.csv')

In [59]:
data.head()

,provider_id,hospital_name,address,city,state,zip_code,county_name,phone_number,measure_id,measure_name,compared_to_national,denominator,score,lower_estimate,higher_estimate,footnote,measure_start_date,measure_end_date
0,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,COMP_HIP_KNEE,Rate of complications for hip/knee replacement...,No Different Than the National Rate,292,3.2,2.1,4.8,NaN,2015-04-01T00:00:00.000,2018-03-31T00:00:00.000
1,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,MORT_30_AMI,Death rate for heart attack patients,No Different Than the National Rate,688,13,11.0,15.5,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
2,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,MORT_30_CABG,Death rate for CABG surgery patients,No Different Than the National Rate,291,4.3,2.6,6.8,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
3,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,MORT_30_COPD,Death rate for COPD patients,No Different Than the National Rate,411,8.8,6.7,11.4,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000
4,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,MORT_30_HF,Death rate for heart failure patients,No Different Than the National Rate,869,12.7,10.7,15.0,NaN,2015-07-01T00:00:00.000,2018-06-30T00:00:00.000

In [69]:
sql = """
select city, count(distinct [provider_id]) as providers
from data
where county_name='JEFFERSON'
group by city
"""

In [70]:
cities = ps.sqldf(sql, locals())

In [71]:
cities

         city  providers
0  BIRMINGHAM          4

In [73]:
data[data['county_name']=='JEFFERSON'].groupby(['city','provider_id']).count()

                        hospital_name  address  state  zip_code  county_name  \
city       provider_id
BIRMINGHAM 10011                   19       19     19        19           19
           10018                   19       19     19        19           19
           10033                   19       19     19        19           19
           10056                   19       19     19        19           19

                        phone_number  measure_id  measure_name  \
city       provider_id
BIRMINGHAM 10011                  19          19            19
           10018                  19          19            19
           10033                  19          19            19
           10056                  19          19            19

                        compared_to_national  denominator  score  \
city       provider_id
BIRMINGHAM 10011                          19           19     19
           10018                          19           19     19
           10033                          19           19     19
           10056                          19           19     19

                        lower_estimate  higher_estimate  footnote  \
city       provider_id
BIRMINGHAM 10011                    19               19         0
           10018                    19               19        10
           10033                    19               19         0
           10056                    19               19         0

                        measure_start_date  measure_end_date
city       provider_id
BIRMINGHAM 10011                        19                19
           10018                        19                19
           10033                        19                19
           10056                        19                19

In [74]:
data[data['county_name']=='JEFFERSON'].groupby(['city','provider_id']).count().groupby(['city']).count()

,hospital_name,address,state,zip_code,county_name,phone_number,measure_id,measure_name,compared_to_national,denominator,score,lower_estimate,higher_estimate,footnote,measure_start_date,measure_end_date
city,,,,,,,,,,,,,,,,
BIRMINGHAM,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4

In [75]:
data[data['county_name']=='JEFFERSON'].groupby(['city','provider_id']).count().groupby(['city'])['hospital_name'].count()

city
BIRMINGHAM    4
Name: hospital_name, dtype: int64